create table users
(
USERID int IDENTITY(1,1) PRIMARY KEY,
LOGINt VARCHAR(20) NOT NULL unique,
PASSWORDt VARCHAr(20) NOT NULL,
EMAIL VARCHAR(20) NOT NULL unique,
USER_STATUS VARCHAR(20) NOT NULL
)
select * from users
